"""initial

Revision ID: 3fb3916983bb
Revises: 
Create Date: 2026-06-15 10:52:59.573851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb3916983bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interns', schema=None) as batch_op:
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
